#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("School_Programme.Resource", IsApplication=true)]

namespace School_Programme
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int About = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int About48 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AddLessonTab = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Keyboard = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ModifyDataTab = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int NumericKeyboard = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int PostponeLessonTab = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Question = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int RemoveLessonTab = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ReviewLessons = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ViewList = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050021
			public const int About = 2131034145;
			
			// aapt resource value: 0x7f050005
			public const int AddLessonFragment_ClassroomET = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int AddLessonFragment_KeyboardSelection = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int AddLesson_PostponedBegginingHourET = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int AddLesson_PostponedEndingHourET = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int AddLesson_PostponedTimeTextOutput = 2131034127;
			
			// aapt resource value: 0x7f050018
			public const int BeggingHourView = 2131034136;
			
			// aapt resource value: 0x7f05000d
			public const int BegginingHourET = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int ChosenType = 2131034114;
			
			// aapt resource value: 0x7f05001c
			public const int ClassroomView = 2131034140;
			
			// aapt resource value: 0x7f050007
			public const int DateData = 2131034119;
			
			// aapt resource value: 0x7f05002e
			public const int DateDataLL = 2131034158;
			
			// aapt resource value: 0x7f05002d
			public const int DateDataSwitch = 2131034157;
			
			// aapt resource value: 0x7f050008
			public const int DayDP = 2131034120;
			
			// aapt resource value: 0x7f050017
			public const int DayView = 2131034135;
			
			// aapt resource value: 0x7f05000e
			public const int EndingHourET = 2131034126;
			
			// aapt resource value: 0x7f050019
			public const int EndingHourView = 2131034137;
			
			// aapt resource value: 0x7f050047
			public const int FrameContainer = 2131034183;
			
			// aapt resource value: 0x7f05002a
			public const int GeneralDataSwitch = 2131034154;
			
			// aapt resource value: 0x7f050000
			public const int IdentificationData = 2131034112;
			
			// aapt resource value: 0x7f05003b
			public const int LabelStatus = 2131034171;
			
			// aapt resource value: 0x7f050001
			public const int LessonNameET = 2131034113;
			
			// aapt resource value: 0x7f050015
			public const int LessonNameView = 2131034133;
			
			// aapt resource value: 0x7f050025
			public const int ListViewModifyLL = 2131034149;
			
			// aapt resource value: 0x7f050037
			public const int ListViewPostponeLL = 2131034167;
			
			// aapt resource value: 0x7f050035
			public const int ModifyBackBtn = 2131034165;
			
			// aapt resource value: 0x7f050032
			public const int ModifyBegginingHourET = 2131034162;
			
			// aapt resource value: 0x7f05002f
			public const int ModifyDayDP = 2131034159;
			
			// aapt resource value: 0x7f050033
			public const int ModifyEndingHourET = 2131034163;
			
			// aapt resource value: 0x7f05002c
			public const int ModifyLessonFragment_ClassroomET = 2131034156;
			
			// aapt resource value: 0x7f050034
			public const int ModifyLessonFragment_KeyboardSelection = 2131034164;
			
			// aapt resource value: 0x7f050026
			public const int ModifyLessonFragment_SortButton = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int ModifyListView = 2131034151;
			
			// aapt resource value: 0x7f05002b
			public const int ModifyPer2Weeks = 2131034155;
			
			// aapt resource value: 0x7f050028
			public const int ModifyScrollViewHolder = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int ModifySelectedItemTV = 2131034153;
			
			// aapt resource value: 0x7f050031
			public const int ModifyTimeSettingsLL = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int ModifyTimeSettingsSw = 2131034160;
			
			// aapt resource value: 0x7f050014
			public const int NextButton = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int Per2WeeksSW = 2131034118;
			
			// aapt resource value: 0x7f05001b
			public const int Per2WeeksView = 2131034139;
			
			// aapt resource value: 0x7f05003f
			public const int PostponeBegginingHourET = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int PostponeEndingHourET = 2131034176;
			
			// aapt resource value: 0x7f050043
			public const int PostponeFrag_BackBtn = 2131034179;
			
			// aapt resource value: 0x7f050041
			public const int PostponeLessonsFragment_KeyboardSelection = 2131034177;
			
			// aapt resource value: 0x7f050039
			public const int PostponeListView = 2131034169;
			
			// aapt resource value: 0x7f05003c
			public const int PostponePostponedDP = 2131034172;
			
			// aapt resource value: 0x7f05003a
			public const int PostponeScrollViewHolder = 2131034170;
			
			// aapt resource value: 0x7f05003e
			public const int PostponeTimePSLL = 2131034174;
			
			// aapt resource value: 0x7f05003d
			public const int PostponeTimePSSW = 2131034173;
			
			// aapt resource value: 0x7f05001d
			public const int PostponedAdapterTV = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int PostponedEndingHourAdapterTV = 2131034144;
			
			// aapt resource value: 0x7f05001e
			public const int PostponedForAdapterTV = 2131034142;
			
			// aapt resource value: 0x7f05000b
			public const int PostponedForDP = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int PostponedForTV = 2131034122;
			
			// aapt resource value: 0x7f05001f
			public const int PostponedStartingHourAdapterTV = 2131034143;
			
			// aapt resource value: 0x7f050009
			public const int PostponedSw = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int PreviousButton = 2131034131;
			
			// aapt resource value: 0x7f050045
			public const int RemoveAllBtn = 2131034181;
			
			// aapt resource value: 0x7f050044
			public const int RemoveLessonFragment_SortButton = 2131034180;
			
			// aapt resource value: 0x7f050046
			public const int RemoveListView = 2131034182;
			
			// aapt resource value: 0x7f050022
			public const int ReviewLessonsBtn = 2131034146;
			
			// aapt resource value: 0x7f050004
			public const int SemesterET = 2131034116;
			
			// aapt resource value: 0x7f05001a
			public const int SemesterView = 2131034138;
			
			// aapt resource value: 0x7f050038
			public const int SortButton = 2131034168;
			
			// aapt resource value: 0x7f050048
			public const int SortingListView = 2131034184;
			
			// aapt resource value: 0x7f050036
			public const int SubmitChangesBtn = 2131034166;
			
			// aapt resource value: 0x7f050042
			public const int SubmitUpdatesPBtn = 2131034178;
			
			// aapt resource value: 0x7f05000c
			public const int TimeData = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int TypeSB = 2131034115;
			
			// aapt resource value: 0x7f050016
			public const int TypeView = 2131034134;
			
			// aapt resource value: 0x7f050023
			public const int UpcommingLessonTextView = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int UpcommingLessonsLV = 2131034148;
			
			// aapt resource value: 0x7f05004a
			public const int ViewAllFragment_ListView = 2131034186;
			
			// aapt resource value: 0x7f050049
			public const int ViewAllFragment_SortButton = 2131034185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddLessonFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LessonVIewRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ModifyLessonFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PostponeLessonsFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RemoveLessonFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ReviewLessons = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SortByLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ViewAllLessonsFragment = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
